#!/bin/sh

# Use neovim for vim if present.
 [ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d" &&
     alias v="nvim" vdiff="nvim -d"

# # ex - archive extractor
# # usage: ex <file>
ex ()
{
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.tar.xz)    tar xJf $1   ;;
      *.tar.zst)   tar xvf $1  ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1   ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *.zpaq)      zpaq x $1      ;;
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

# Some aliases
alias mkd="mkdir -pv"
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -vI"
alias ll="ls -al"
alias la="ls -a"
alias ka="killall"
alias reload="source ~/.config/zsh/.zshrc"
alias sdn="shutdown now"
alias bell="mpv ~/music/bell.m4a"

# Common apps
alias r="ranger"
alias lf="lfub"
alias md="litemdview"

# Adding color
alias ls='ls -hN --color=auto --group-directories-first'
alias dir='dir -hN --color=auto --group-directories-first'
alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias bat="bat --theme=OneHalfDark"
alias cat="bat --theme=OneHalfDark"

# Internet
alias ytd="yt-dlp --add-metadata -i"
alias yta="yt-dlp -x -f bestaudio/best"
alias yt="ytfzf"
alias ds="subliminal download -s -f -l \"en\""

# Suckless Hacking
alias edit="vim config.h"
alias doit="sudo make clean install"
alias save="cp config.h config.def.h"
alias fallback="cp config.def.h config.h"
alias change="diff config.def.h config.h"

# Pacman
alias p="sudo pacman"
alias ps="sudo pacman -S"
alias pr="sudo pacman -Rns"
alias pss="pacman -Ss"
alias psi="pacman -Si"
alias pq="pacman -Q"
alias pqs="pacman -Qs"
alias pqi="pacman -Qi"
alias update="yay -Syu"

# Shortcuts
alias vimrc="nvim ~/.vimrc"
alias nvimrc="nvim ~/.config/nvim/init.vim"

# Config Shortcuts
alias cf="cd ~/.config/"
alias cfd="cd ~/.config/dwm/"
alias cfu="nvim ~/.config/newsboat/urls"

# Other Shortcuts
alias game="ka kdeconnectd redshift-gtk lxpolkit dunst mailspring"
alias screentest="mpv --no-config --video-sync=display-resample --hwdec=vaapi ~/media/check-screen-tearing.mp4"

se() { du -a ~/.scripts/* | awk '{print $2}' | fzf | xargs -r $EDITOR ;}
