#!/bin/sh

clock=$(date '+%I')

# You can use a different emoji or glyph as time icon depending on the hour
# case "$clock" in
# 	"00") timeIcon="🕛" ;;
# 	"01") timeIcon="🕐" ;;
# 	"02") timeIcon="🕑" ;;
# 	"03") timeIcon="🕒" ;;
# 	"04") timeIcon="🕓" ;;
# 	"05") timeIcon="🕔" ;;
# 	"06") timeIcon="🕕" ;;
# 	"07") timeIcon="🕖" ;;
# 	"08") timeIcon="🕗" ;;
# 	"09") timeIcon="🕘" ;;
# 	"10") timeIcon="🕙" ;;
# 	"11") timeIcon="🕚" ;;
# 	"12") timeIcon="🕛" ;;
# esac

# Or you can just use a static time con
dayIcon=""
timeIcon=""

case $BLOCK_BUTTON in
	1) notify-send "This Month" "$(cal --color=always | sed "s/..7m/<b><span color=\"red\">/;s/..27m/<\/span><\/b>/")" && notify-send "Appointments" "$(calcurse -d3)" ;;
	2) setsid -f "$TERMINAL" -e calcurse ;;
    # 
	3) notify-send " Time/date module" "\- Left click to show upcoming appointments for the next three days via \`calcurse -d3\` and show the month via \`cal\`
- Middle click opens calcurse if installed" ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

# date "+ %Y %b %d (%a) $icon%I:%M%p"
date "+$dayIcon %a %b %d-%m-%y | $timeIcon %H:%M"
# date "+📅%a %b %d-%m-%y $icon%T"
