#!/bin/sh

# Displays number of unread news items and an loading icon if updating.
# When clicked, brings up `newsboat`.

stackTag = "statusNews"

case $BLOCK_BUTTON in
    1) setsid "$TERMINAL" -e newsboat ;;
    2) dunstify -a "showNews" -u low -i "news-subscribe" -h string:x-dunst-stack-tag:$stackTag \
"News module" "\- Shows unread news items
- Shows  if updating with \`newsup\`
- Left click opens newsboat
- Right click syncs RSS feeds
<b>Note:</b> Only one instance of newsboat (including updates) may be running at a time." ;;
	3) setsid -f newsup >/dev/null exit ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

 cat /tmp/newsupdate 2>/dev/null || echo "$(newsboat -x print-unread | awk '{ if($1>0) print " " $1}')$(cat "${XDG_CONFIG_HOME:-$HOME/.config}"/newsboat/.update 2>/dev/null)"
