#!/bin/sh

# Prints the current volume or 🔇 if muted.

case $BLOCK_BUTTON in
	1) setsid -f "$TERMINAL" -e pulsemixer ;;
	2) pamixer -t ;;
	4) pamixer --allow-boost -i 1 ;;
	5) pamixer --allow-boost -d 1 ;;
	3) notify-send " Volume module" "\- Shows volume 🔊,  if muted.
- Middle click to mute.
- Scroll to change." ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

# Arbitrary but unique message tag
msgTag="statusVolume"

# [ $(pamixer --get-mute) = true ] && echo 🔇 && exit
[ $(pamixer --get-mute) = true ] && echo "" &&
    # Show the sound muted notification
    dunstify -a "changeVolume" -u low -i audio-volume-muted -h string:x-dunst-stack-tag:$msgTag "Volume muted" &&
    exit

vol="$(pamixer --get-volume)"

# if [ "$vol" -gt "70" ]; then
# 	icon="🔊"
# elif [ "$vol" -lt "30" ]; then
# 	icon="🔈"
# else
# 	icon="🔉"
# fi

if [ "$vol" -gt "50" ]; then
	icon=""
    # Show the volume notification
    dunstify -a "changeVolume" -u low -i audio-volume-high -h string:x-dunst-stack-tag:$msgTag \
    -h int:value:"$vol" "Volume: ${vol}%"
# elif [ "$vol" -lt "30" ]; then
# 	icon="奔 "
elif [ "$vol" -eq "0" ]; then
    icon=""
    # Show the sound muted notification
    dunstify -a "changeVolume" -u low -i audio-volume-muted -h string:x-dunst-stack-tag:$msgTag "Volume muted"
else
	icon=""
    # Show the volume notification
    dunstify -a "changeVolume" -u low -i audio-volume-medium -h string:x-dunst-stack-tag:$msgTag \
    -h int:value:"$vol" "Volume: ${vol}%"
fi

echo "$icon $vol%"
