#!/bin/sh

# Colors used for printing
NC='\033[0m'
WHITE='\033[1;37m'
BLACK='\033[0;30m'
BLUE='\033[0;34m'
L_BLUE='\033[1;34m'
GREEN='\033[0;32m'
L_GREEN='\033[1;32m'
CYAN='\033[0;36m'
L_CYAN='\033[1;36m'
RED='\033[0;31m'
L_RED='\033[1;31m'
PURPLE='\033[0;35m'
L_PURPLE='\033[1;35m'
YELLOW='\033[0;33m'
L_YELLOW='\033[1;33m'
GRAY='\033[1;30m'
L_GRAY='\033[0;37m'

for x in {0..8}; do for i in {30..37}; do for a in {40..47}; do echo -ne "\e[$x;$i;$a""m\\\e[$x;$i;$a""m\e[0;37;40m "; done; echo; done; done; echo ""


echo -e "\033[0mNC (No color)"
echo -e "\033[1;37mWHITE\t\033[0;30mBLACK"
echo -e "\033[0;34mBLUE\t\033[1;34mLIGHT_BLUE"
echo -e "\033[0;32mGREEN\t\033[1;32mLIGHT_GREEN"
echo -e "\033[0;36mCYAN\t\033[1;36mLIGHT_CYAN"
echo -e "\033[0;31mRED\t\033[1;31mLIGHT_RED"
echo -e "\033[0;35mPURPLE\t\033[1;35mLIGHT_PURPLE"
echo -e "\033[0;33mYELLOW\t\033[1;33mLIGHT_YELLOW"
echo -e "\033[1;30mGRAY\t\033[0;37mLIGHT_GRAY"
